### ISSUE TITLE
Tell us about CABECEO

### ISSUE THREAD

**Issue by susalev** [ElshazlyA/Tango#2]
@ElshazlyA I cannot imaging an article about tango without ___Tango Manners___

**Comment by ElshazlyA** [comment]
Cabeceo is the way of inviting the partner for a dance. when a new Tanda starts, Tango leaders will do a Mirada ( the look at other dancers)- When Eye contact is maintained ( then the leader will do the Cabeceo). when the woman Nod her head to the invitation. Then they both meet at the dancing floor and start dancing. If a woman Ignore the Mirada ( No eye contact maintained)- means that the Cabeceo ( request for a dance) is not approved ( She does not want to dance) .

**Comment by ElshazlyA** [comment]
Please find a video to illustrate the Cabeceo- https://youtu.be/0c89r9vVr9A
